sudo: true
language: python
cache:
  pip: true
services:
  - redis-server
python:
  - "3.6.2"
before_script:
  - psql -c 'create database travisci;' -U postgres
install:
  - pip install -r requirements/test.txt
script: "python manage.py test --parallel"
notifications:
  email:
    recipients:
      - tylermalin@gmail.com
    on_success: never # default: change
    on_failure: always # default: always
